name: weatherapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.4.0
  intl: ^0.18.1
  readmore: ^2.1.0
  flutter_slidable: ^3.0.0
  url_launcher: ^6.0.20
  flutter_dotenv: ^5.0.2
  timezone: ^0.9.2
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.0.16
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_launcher_icons_maker: "^0.10.1"

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/images/pc_300.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - dotenv

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Koulen
      fonts:
        - asset: fonts/Koulen-Regular.ttf
    - family: MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf
